package com.health.healthcareappointmentbookingsystem.entity;

public enum Specialization {
    GENERAL_PRACTITIONER,CARDIOLOGY,NEUROLOGY ,INTERNAL_MEDICINE,DERMATOLOGY,PEDIATRICS,ORTHOPEDICS,PSYCHIATRY,	ENT,OPHTHALMOLOGY,GYNECOLOGY,UROLOGY,GENERAL_SURGERY,DENTISTRY,	ENDOCRINOLOGY
}
